# render.yaml
services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free  # Remove for paid plans
    region: singapore  # Choose closest to your users
    
    # Build settings
    buildCommand: |
      npm install
      npm run build
      
    # Start command (matches your package.json)
    startCommand: pm2-runtime start index.js --name malvin-xd
    
    # Health check (critical for WhatsApp connection stability)
    healthCheckPath: /
    healthCheckTimeoutSeconds: 30
    
    # Auto-deploy from GitHub
    autoDeploy: true
    
    # Environment variables (add these in Render dashboard too)
    envVars:
      - key: DISPLAY
        value: ":99"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
